version: '3'

services:
  postgres:
    image: 'bitnami/postgresql'
    restart: 'always'
    environment:
      POSTGRESQL_USER: 'docker'
      POSTGRESQL_PASSWORD: 'docker'
      POSTGRESQL_DATABASE: 'zetashort'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

volumes:
  postgresql_data:
    driver: local
